### ISSUE TITLE
Pass Blargg's LCD timing test

### ISSUE THREAD

**Issue by Elizafox** [supergameherm/supergameherm#15]
Presently turning on the LCD "starts too late in the scan line." This should probably be fixed, and is needed to pass #14 at any rate.

**Comment by awilfox** [comment]
[This resource](http://gameboy.mongenel.com/dmg/istat98.txt) has more information about timings of the STAT interrupt.  The MESS emulator has an [entire ASCII state machine of STAT](http://git.redump.net/mame/plain/src/mess/drivers/gb.c).  There are a few other interesting interrupt timing docs such as [this odd wiki article](https://code.google.com/p/megaboy/wiki/Interrupts) and some [simplified timing docs that aren't exactly accurate](http://imrannazar.com/GameBoy-Emulation-in-JavaScript:-GPU-Timings).  But the thing is, no matter how I hammer at it, I can't make it pass.  This is primarily because [Blargg's open source test is missing oam_bug.inc](https://github.com/isuru-c-p/AsobiOtoko/blob/master/ROMs/tests/oam_bug/source/1-lcd_sync.s), so I can't see what exactly 'delay' is or what the count is.  109 is before LY changes, 110 is right after LY changes, but 110 /what/?  It's 452 clocks or 113 ticks between LY; does the initial start up phase lose 4 clocks / 1 tick somewhere?  Even setting curr_clk = 4 in the enabling method still fails with "too early"... in fact, curr_clk = 455 even says "too early" so I think I'm missing something huge here.

**Comment by Elizafox** [comment]
Duplicate of #22
